version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: shopify_automation_db
    environment:
      POSTGRES_DB: shopify_automation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopify_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: shopify_automation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shopify_network

  # Python Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopify_automation_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/shopify_automation
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - shopify_network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shopify_automation_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - shopify_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  shopify_network:
    driver: bridge
